"""Tiny teacher adapter runner skeleton."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from atlas3r.io.session import validate_session
from atlas3r.models.adapters.contracts import AdapterAvailability, AdapterStatus
from atlas3r.models.adapters.fixture_teacher_adapter import (
    ADAPTER_NAME as FIXTURE_CUBE_ROOM_ADAPTER_NAME,
)
from atlas3r.models.adapters.fixture_teacher_adapter import (
    FixtureCubeRoomTeacherAdapter,
)
from atlas3r.models.adapters.registry import get_adapter_status


@dataclass(frozen=True)
class AdapterRunResult:
    adapter_status: AdapterStatus
    input_session: Path
    output_cache: Path


class AdapterRunError(RuntimeError):
    """Raised when an adapter run cannot produce a TeacherPrediction cache."""

    def __init__(
        self,
        *,
        adapter_name: str,
        status: str,
        reason: str,
        guidance: str,
    ) -> None:
        super().__init__(
            "Adapter run failed: "
            f"adapter={adapter_name} status={status} reason={reason} guidance={guidance}"
        )
        self.adapter_name = adapter_name
        self.status = status
        self.reason = reason
        self.guidance = guidance


def run_adapter_to_cache(
    *,
    adapter_name: str,
    input_session: str | Path,
    output_cache: str | Path,
    store_arrays: bool = False,
) -> AdapterRunResult:
    """Validate the session and write a teacher prediction cache when available."""
    input_path = Path(input_session)
    try:
        status = get_adapter_status(adapter_name)
    except KeyError as exc:
        raise AdapterRunError(
            adapter_name=adapter_name,
            status="unknown",
            reason=str(exc),
            guidance="Run `atlas3r adapters list` and choose a known adapter.",
        ) from exc

    try:
        session = validate_session(input_path)
    except ValueError as exc:
        raise AdapterRunError(
            adapter_name=status.name,
            status=status.availability,
            reason=str(exc),
            guidance="Provide a valid Phase 0B `.atlas3r` session folder.",
        ) from exc

    if status.availability == AdapterAvailability.UNAVAILABLE.value:
        raise AdapterRunError(
            adapter_name=status.name,
            status=status.availability,
            reason=status.reason or "adapter dependencies are unavailable",
            guidance=status.install_hint or "Install the optional adapter dependencies.",
        )
    if status.availability == AdapterAvailability.STUB_ONLY.value:
        raise AdapterRunError(
            adapter_name=status.name,
            status=status.availability,
            reason=status.reason or "adapter inference is not implemented",
            guidance=(
                "Implement the adapter behind GeometryTeacherAdapter.predict before running; "
                f"{status.install_hint or 'keep third-party code and weights external.'}"
            ),
        )

    output_path = Path(output_cache)
    if status.name == FIXTURE_CUBE_ROOM_ADAPTER_NAME:
        from atlas3r.io.teacher_cache import write_teacher_prediction_cache

        try:
            prediction = FixtureCubeRoomTeacherAdapter().predict_from_session(session)
            write_teacher_prediction_cache(
                prediction,
                output_path,
                status,
                store_arrays=store_arrays,
            )
        except ValueError as exc:
            raise AdapterRunError(
                adapter_name=status.name,
                status=status.availability,
                reason=str(exc),
                guidance=(
                    "Use a valid Phase 0B synthetic cube-room `.atlas3r` session generated by "
                    "`atlas3r smoke synthetic-cube-room`."
                ),
            ) from exc
        return AdapterRunResult(
            adapter_status=status,
            input_session=input_path,
            output_cache=output_path,
        )

    raise AdapterRunError(
        adapter_name=status.name,
        status=status.availability,
        reason="No runnable adapter implementation is registered for this available status",
        guidance=(
            "Wire the adapter to produce TeacherPrediction, then write it with "
            "write_teacher_prediction_cache."
        ),
    )


__all__ = ["AdapterRunError", "AdapterRunResult", "run_adapter_to_cache"]
