"""TSDF/surfel fusion, meshing, and map chunks."""

from atlas3r.mapping.cpu_tsdf import (
    TSDFCubeRoomSmokeResult,
    TSDFSurface,
    TSDFVolume,
    evaluate_surface_against_synthetic_cube_room,
    extract_tsdf_surface,
    integrate_depth_observation,
    integrate_synthetic_cube_room_scene,
    run_tsdf_cube_room_smoke,
    write_tsdf_cube_room_smoke,
)
from atlas3r.mapping.mesh_sidecar import (
    DEFAULT_MAX_SURFACE_SAMPLES,
    MESH_SIDECAR_FILENAME,
    MESH_SIDECAR_FORMAT_NAME,
    MESH_SIDECAR_FORMAT_VERSION,
    load_tsdf_surface_artifacts,
    load_tsdf_surface_mesh_sidecar,
    mesh_chunk_from_tsdf_surface,
    tsdf_surface_mesh_sidecar_record,
    write_tsdf_surface_mesh_sidecar,
    write_tsdf_surface_mesh_sidecar_from_artifacts,
)
from atlas3r.mapping.observations import (
    DepthObservation,
    depth_observation_from_synthetic_frame,
)
from atlas3r.mapping.teacher_cache_replay import (
    TeacherCacheTSDFReplayFrame,
    TeacherCacheTSDFReplayResult,
    depth_observation_from_teacher_cache_frame,
    load_teacher_cache_tsdf_replay_frames,
    run_teacher_cache_tsdf_replay,
    write_teacher_cache_tsdf_replay,
)
from atlas3r.mapping.tsdf_output_inspection import (
    TSDF_OUTPUT_INSPECTION_FORMAT_NAME,
    TSDF_OUTPUT_INSPECTION_FORMAT_VERSION,
    TSDF_OUTPUT_INSPECTION_MODES,
    format_tsdf_output_folder_inspection,
    tsdf_output_folder_inspection_record,
)
from atlas3r.mapping.world_map_sidecar import (
    DEFAULT_WORLD_MAP_ID,
    DETERMINISTIC_CREATED_AT_NS,
    REQUIRED_TRUTH_BOUNDARY_FLAGS,
    WORLD_MAP_SIDECAR_FILENAME,
    WORLD_MAP_SIDECAR_FORMAT_NAME,
    WORLD_MAP_SIDECAR_FORMAT_VERSION,
    format_world_map_sidecar_inspection,
    load_tsdf_world_map_sidecar,
    tsdf_world_map_sidecar_record,
    world_map_from_mesh_sidecar,
    write_tsdf_world_map_sidecar_from_artifacts,
    write_tsdf_world_map_sidecar_from_mesh_sidecar,
)

__all__ = [
    "TSDFCubeRoomSmokeResult",
    "TSDFSurface",
    "TSDFVolume",
    "TeacherCacheTSDFReplayFrame",
    "TeacherCacheTSDFReplayResult",
    "DepthObservation",
    "DEFAULT_MAX_SURFACE_SAMPLES",
    "TSDF_OUTPUT_INSPECTION_FORMAT_NAME",
    "TSDF_OUTPUT_INSPECTION_FORMAT_VERSION",
    "TSDF_OUTPUT_INSPECTION_MODES",
    "DEFAULT_WORLD_MAP_ID",
    "DETERMINISTIC_CREATED_AT_NS",
    "MESH_SIDECAR_FILENAME",
    "MESH_SIDECAR_FORMAT_NAME",
    "MESH_SIDECAR_FORMAT_VERSION",
    "REQUIRED_TRUTH_BOUNDARY_FLAGS",
    "WORLD_MAP_SIDECAR_FILENAME",
    "WORLD_MAP_SIDECAR_FORMAT_NAME",
    "WORLD_MAP_SIDECAR_FORMAT_VERSION",
    "depth_observation_from_synthetic_frame",
    "depth_observation_from_teacher_cache_frame",
    "evaluate_surface_against_synthetic_cube_room",
    "extract_tsdf_surface",
    "format_tsdf_output_folder_inspection",
    "format_world_map_sidecar_inspection",
    "integrate_depth_observation",
    "integrate_synthetic_cube_room_scene",
    "load_teacher_cache_tsdf_replay_frames",
    "load_tsdf_world_map_sidecar",
    "load_tsdf_surface_artifacts",
    "load_tsdf_surface_mesh_sidecar",
    "mesh_chunk_from_tsdf_surface",
    "run_teacher_cache_tsdf_replay",
    "run_tsdf_cube_room_smoke",
    "tsdf_surface_mesh_sidecar_record",
    "tsdf_output_folder_inspection_record",
    "tsdf_world_map_sidecar_record",
    "world_map_from_mesh_sidecar",
    "write_teacher_cache_tsdf_replay",
    "write_tsdf_surface_mesh_sidecar",
    "write_tsdf_surface_mesh_sidecar_from_artifacts",
    "write_tsdf_world_map_sidecar_from_artifacts",
    "write_tsdf_world_map_sidecar_from_mesh_sidecar",
    "write_tsdf_cube_room_smoke",
]
